FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
    iproute2 \
    iptables \
    nftables \
    curl \
    iputils-ping \
    dnsutils \
    net-tools \
    dnsmasq \
    psmisc \
    python3 \
    python3-pip \
    python3-dev \
    libnetfilter-queue-dev \
    strace \
    tcpdump \
    kmod \
    && pip3 install --break-system-packages NetfilterQueue \
    && rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
