#!/usr/sbin/nft -f

flush ruleset

table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        # NAT for traffic leaving via border gateways
        oifname "eth1" masquerade
        oifname "eth2" masquerade
        # NAT for traffic leaving via Docker bridge (real internet)
        oifname "eth0" masquerade
    }
}
